### ISSUE TITLE
Adding release tags

### ISSUE THREAD

**Issue by anton-khodak** [erasche/galaxyxml#5]
I would like to create a Debian package of `galaxyxml`, I see that the current version (0.2.3) is different from the latest release (0.1), it would be nice if you could create a release tag for the latest stable version. The package can not be built for Python 3 due to outdatedness of the release code

**Comment by anton-khodak** [comment]
It's blocking packaging of `argparse2tool`

**Comment by hexylena** [comment]
Yep, not a problem. Missed this over the holiday weekend, will get to this week.

**Comment by hexylena** [comment]
Done. Tagged releases are now tested on travis and automatically posted to pypi.
